// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACmRil2oZ7FDuppVZV6qeXSU7ZCTAYX10',
    appId: '1:455872966227:web:ab10af81058300c76220a6',
    messagingSenderId: '455872966227',
    projectId: 'crudtut-1',
    authDomain: 'crudtut-1.firebaseapp.com',
    storageBucket: 'crudtut-1.appspot.com',
    measurementId: 'G-8NTZ8375CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Hg47roULw6DCZwTDivpcX1XN9c_qbs8',
    appId: '1:455872966227:android:84f923fa71cc8d0e6220a6',
    messagingSenderId: '455872966227',
    projectId: 'crudtut-1',
    storageBucket: 'crudtut-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVzYH51qAtGhjEf85TWJDOR_Z6Wi1hRJ4',
    appId: '1:455872966227:ios:0ea4b2a523fe8b026220a6',
    messagingSenderId: '455872966227',
    projectId: 'crudtut-1',
    storageBucket: 'crudtut-1.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );
}
